# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EinhasadBar < Formula
  desc "macOS menu-bar manager for local dev stacks, configured via YAML"
  homepage "https://github.com/einhasad/einhasad-bar"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/einhasad/einhasad-bar/releases/download/v0.1.0/einhasad-bar_0.1.0_darwin_arm64.tar.gz"
    sha256 "7cd2b6a935dc39d0f54bba6cc7ec004dde61430af221b5f0b3195f65db2fcc12"

    define_method(:install) do
      bin.install "einhasad-bar"
    end
  end

  def caveats
    <<~EOS
      einhasad-bar is a menu-bar app. Register a project config, then launch it:
        einhasad-bar register /path/to/einhasad-bar.yaml
        einhasad-bar &
      To start it at login, add it under
        System Settings → General → Login Items.
    EOS
  end
end
